### ISSUE TITLE
Missing local variable definitions in variable.tf

### ISSUE THREAD

**Issue by xbbpbbp** [terraform-aviatrix-modules/terraform-aviatrix-azure-spoke#10]
Seem to be Missing
```
  cidrbits   = tonumber(split("/", var.cidr)[1])
  newbits    = 26 - local.cidrbits
  netnum     = pow(2, local.newbits)
```
in variable.tf > locals

**Comment by Dennizz** [comment]
Thanks for bringing this to our attention. I have rectified it and released a new version 3.0.2 and pulled version 3.0.1 that contained the issue.
