### ISSUE TITLE
enable_active_mesh errored out

### ISSUE THREAD

**Issue by satya5186** [terraform-aviatrix-modules/terraform-aviatrix-azure-spoke#15]
Getting this error while using spoke modules, need to fix the code 

`Error: Unsupported argument
│ 
│   on .terraform/modules/spoke_azure_1/main.tf line 27, in resource "aviatrix_spoke_gateway" "default":
│   27:   enable_active_mesh                    = var.active_mesh
│ 
│ An argument named "enable_active_mesh" is not expected here.`

**Comment by Dennizz** [comment]
Hi Satya, thanks for reporting this. As per controller version 6.6, enable_active_mesh is no longer a supported argument for the aviatrix_spoke_gateway which is part of this module. That is what's causing this error to arise.
In stead of updating this module, we have release a multi-cloud spoke module that is usable for Azure as well as other clouds. I would like to suggest to start using that one. Migrating shouldn't be to complex, but I'm happy to help if you need support.

You can find the module here:
https://github.com/terraform-aviatrix-modules/terraform-aviatrix-mc-spoke

Some small behavior changes that you have to account for:
- Prefix/suffix addition of "avx-" and "-spoke" to the name has been removed. If you were using this (which is default), you would have to add these to the name to prevent a change in the name.
- As this module is multi-cloud, you need to add an argument to inform the module for which cloud it is deploying. It's very simple. Just add the below code to calling the module.

```cloud = "azure"```

Please let me know if you have any questions.

**Comment by satya5186** [comment]
Hi Dennis,

Thanks for the response. I will take a look at MC modules.

Regards,
Satya

From: Dennis Hagens ***@***.***>
Date: Wednesday, March 9, 2022 at 4:11 AM
To: terraform-aviatrix-modules/terraform-aviatrix-azure-spoke ***@***.***>
Cc: Satyanarayana Prasad Chalavadi ***@***.***>, Author ***@***.***>
Subject: Re: [terraform-aviatrix-modules/terraform-aviatrix-azure-spoke] enable_active_mesh errored out (Issue #15)

Hi Satya, thanks for reporting this. As per controller version 6.6, enable_active_mesh is no longer a supported argument for the aviatrix_spoke_gateway which is part of this module. That is what's causing this error to arise.
In stead of updating this module, we have release a multi-cloud spoke module that is usable for Azure as well as other clouds. I would like to suggest to start using that one. Migrating shouldn't be to complex, but I'm happy to help if you need support.

You can find the module here:
https://github.com/terraform-aviatrix-modules/terraform-aviatrix-mc-spoke<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fterraform-aviatrix-modules%2Fterraform-aviatrix-mc-spoke&data=04%7C01%7Cschalavadi%40aviatrix.com%7Ca7929c00d68943eb6f1008da01b53256%7C4780055ece374f02b33dfdad8493a4b6%7C0%7C0%7C637824175005309581%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CdnkuNfT06b%2Bxr26jbcCwbAUGwVCp1fSuz6h8%2FOHd74%3D&reserved=0>

Some small behavior changes that you have to account for:

  *   Prefix/suffix addition of "avx-" and "-spoke" to the name has been removed. If you were using this (which is default), you would have to add these to the name to prevent a change in the name.
  *   As this module is multi-cloud, you need to add an argument to inform the module for which cloud it is deploying. It's very simple. Just add the below code to calling the module.

cloud = "azure"

Please let me know if you have any questions.

**Comment by Dennizz** [comment]
Let me know if you need help. Closing this issue.
